branch-defaults:
  default:
    environment: site-test-23-05-9h47-d
global:
  application_name: site-test-23-05-9h47
  default_ec2_keyname: null
  default_platform: 64bit Amazon Linux 2016.03 v2.1.0 running Python 3.4
  default_region: us-west-2
  profile: eb-cli
  sc: null
